function cfg(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase env missing');return{url:url.replace(/\/$/,''),key}}
async function db(path,{method='GET',body,prefer}={}){const{url,key}=cfg();const headers={apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};if(prefer)headers.Prefer=prefer;const r=await fetch(`${url}/rest/v1/${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t.slice(0,300)}`);return t?JSON.parse(t):null}
function moneyToNumber(v=''){const n=Number(String(v).replace(/[^0-9.]/g,''));return Number.isFinite(n)?n:null}
function parseJsonLd(html){for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const p=JSON.parse(m[1].trim()),items=Array.isArray(p)?p:[p];for(const x of items)if(x&&(x['@type']==='Product'||x.name)&&x.offers)return x}catch{}}return null}
function first(html,re){const m=html.match(re);return m?.[1]||null}
function liveState(html){const ld=parseJsonLd(html),offers=Array.isArray(ld?.offers)?ld.offers[0]:ld?.offers;const price=moneyToNumber(offers?.price)||moneyToNumber(first(html,/data-price-amount=["']([^"']+)["']/i))||moneyToNumber(first(html,/itemprop=["']price["'][^>]+content=["']([^"']+)["']/i));const a=String(offers?.availability||'');const inStock=a?/InStock/i.test(a):!/Agotado|Sin existencias/i.test(html);return{price,inStock}}
function roundUp(v,step){step=Number(step)>0?Number(step):1;return Math.ceil(Number(v)/step)*step}
function sale(cost,rule){return roundUp(Number(cost)*Number(rule?.multiplier||1)+Number(rule?.fixed_markup||0),rule?.round_to||1)}
async function fetchHtml(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; UFRACommerceCheckout/1.0)','accept-language':'es-MX,es;q=0.9'},cache:'no-store',signal:controller.signal});if(!r.ok)throw new Error(`UFRA ${r.status}`);return await r.text()}finally{clearTimeout(timer)}}
function clean(v,max=200){return String(v||'').trim().slice(0,max)}
export default async function handler(req,res){let orderId=null;try{if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});const body=req.body||{},items=Array.isArray(body.items)?body.items:[],customer=body.customer||{},address=body.shippingAddress||{};if(!items.length||items.length>20)return res.status(400).json({ok:false,error:'Cart must contain 1-20 items'});const ids=[...new Set(items.map(x=>String(x.id||'')).filter(x=>/^[0-9a-f-]{36}$/i.test(x)))];if(ids.length!==items.length)return res.status(400).json({ok:false,error:'Invalid product id in cart'});const name=clean(customer.name,160),email=clean(customer.email,200),phone=clean(customer.phone,60);if(!name||!email||!phone)return res.status(400).json({ok:false,error:'Nombre, email y teléfono son obligatorios'});const shipping={line1:clean(address.line1,200),line2:clean(address.line2,200),city:clean(address.city,120),state:clean(address.state,120),postalCode:clean(address.postalCode,20),country:'MX'};if(!shipping.line1||!shipping.city||!shipping.state||!shipping.postalCode)return res.status(400).json({ok:false,error:'Dirección de envío incompleta'});
const stores=await db('stores?slug=eq.ufra-commerce&select=id&limit=1'),storeId=stores?.[0]?.id;if(!storeId)throw new Error('Store not found');const providers=await db('fulfillment_providers?slug=eq.pyem&active=eq.true&select=id&limit=1'),providerId=providers?.[0]?.id||null;const rules=await db(`pricing_rules?store_id=eq.${storeId}&active=eq.true&select=multiplier,fixed_markup,round_to,priority&order=priority.asc&limit=1`),rule=rules?.[0];if(!rule)throw new Error('Pricing rule not found');const rows=await db(`store_products?store_id=eq.${storeId}&published=eq.true&product_id=in.(${ids.join(',')})&select=product_id,supplier_product_id,supplier_products(source_url)&limit=20`);const byId=new Map((rows||[]).map(r=>[r.product_id,r]));const verified=[];for(const item of items){const row=byId.get(String(item.id));if(!row)return res.status(409).json({ok:false,error:'Uno de los productos ya no está disponible'});const s=Array.isArray(row.supplier_products)?row.supplier_products[0]:row.supplier_products;let live;try{live=liveState(await fetchHtml(s.source_url))}catch{return res.status(409).json({ok:false,error:'No se pudo verificar un producto con el proveedor'});}if(!live.inStock||live.price==null)return res.status(409).json({ok:false,error:'Uno de los productos está agotado o no tiene precio verificable'});const qty=Math.max(1,Math.min(10,Number(item.qty)||1)),unitPrice=sale(live.price,rule);verified.push({product_id:row.product_id,supplier_product_id:row.supplier_product_id,quantity:qty,unit_price:unitPrice,supplier_cost_snapshot:live.price})}
const subtotal=verified.reduce((sum,x)=>sum+x.unit_price*x.quantity,0),shippingAmount=0,total=subtotal+shippingAmount,verifiedAt=new Date().toISOString();const created=await db('orders?select=id,status,payment_status,total,currency',{method:'POST',prefer:'return=representation',body:{store_id:storeId,status:'pending_payment',payment_method:'stripe',payment_status:'pending',subtotal,shipping_amount:shippingAmount,total,currency:'MXN',customer_name:name,customer_email:email,customer_phone:phone,shipping_address:shipping,fulfillment_provider_id:providerId}});orderId=created?.[0]?.id;if(!orderId)throw new Error('Order was not created');await db('order_items',{method:'POST',prefer:'return=minimal',body:verified.map(x=>({...x,order_id:orderId,supplier_stock_verified_at:verifiedAt}))});res.status(201).json({ok:true,order:{id:orderId,status:'pending_payment',paymentStatus:'pending',subtotal,shippingAmount,total,currency:'MXN',verifiedAt}})}catch(e){if(orderId){try{await db(`orders?id=eq.${orderId}`,{method:'DELETE',prefer:'return=minimal'})}catch{}}res.status(500).json({ok:false,error:e.message})}}
