function cfg(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase env missing');return{url:url.replace(/\/$/,''),key}}
async function db(path){const{url,key}=cfg();const r=await fetch(`${url}/rest/v1/${path}`,{headers:{apikey:key,Authorization:`Bearer ${key}`},cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t.slice(0,300)}`);return t?JSON.parse(t):null}
function moneyToNumber(v=''){const n=Number(String(v).replace(/[^0-9.]/g,''));return Number.isFinite(n)?n:null}
function parseJsonLd(html){for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const p=JSON.parse(m[1].trim()),items=Array.isArray(p)?p:[p];for(const x of items)if(x&&(x['@type']==='Product'||x.name)&&x.offers)return x}catch{}}return null}
function first(html,re){const m=html.match(re);return m?.[1]||null}
function liveState(html){const ld=parseJsonLd(html),offers=Array.isArray(ld?.offers)?ld.offers[0]:ld?.offers;const price=moneyToNumber(offers?.price)||moneyToNumber(first(html,/data-price-amount=["']([^"']+)["']/i))||moneyToNumber(first(html,/itemprop=["']price["'][^>]+content=["']([^"']+)["']/i));const a=String(offers?.availability||'');const inStock=a?/InStock/i.test(a):!/Agotado|Sin existencias/i.test(html);return{price,inStock}}
function roundUp(v,step){step=Number(step)>0?Number(step):1;return Math.ceil(Number(v)/step)*step}
function sale(cost,rule){return roundUp(Number(cost)*Number(rule?.multiplier||1)+Number(rule?.fixed_markup||0),rule?.round_to||1)}
async function fetchHtml(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; UFRACommerceCheckout/1.0)','accept-language':'es-MX,es;q=0.9'},cache:'no-store',signal:controller.signal});if(!r.ok)throw new Error(`UFRA ${r.status}`);return await r.text()}finally{clearTimeout(timer)}}
export default async function handler(req,res){try{if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});const items=Array.isArray(req.body?.items)?req.body.items:[];if(!items.length||items.length>20)return res.status(400).json({ok:false,error:'Cart must contain 1-20 items'});const ids=[...new Set(items.map(x=>String(x.id||'')).filter(x=>/^[0-9a-f-]{36}$/i.test(x)))];if(ids.length!==items.length)return res.status(400).json({ok:false,error:'Invalid product id in cart'});const stores=await db('stores?slug=eq.ufra-commerce&select=id&limit=1'),storeId=stores?.[0]?.id;if(!storeId)throw new Error('Store not found');const rules=await db(`pricing_rules?store_id=eq.${storeId}&active=eq.true&select=multiplier,fixed_markup,round_to,priority&order=priority.asc&limit=1`),rule=rules?.[0];if(!rule)throw new Error('Pricing rule not found');const rows=await db(`store_products?store_id=eq.${storeId}&published=eq.true&product_id=in.(${ids.join(',')})&select=product_id,supplier_product_id,products(canonical_name,brand,image_url),supplier_products(source_url,supplier_sku)&limit=20`);const byId=new Map((rows||[]).map(r=>[r.product_id,r]));const results=[];for(const item of items){const row=byId.get(item.id);if(!row){results.push({id:item.id,valid:false,reason:'Producto no disponible'});continue}const p=Array.isArray(row.products)?row.products[0]:row.products,s=Array.isArray(row.supplier_products)?row.supplier_products[0]:row.supplier_products;try{const html=await fetchHtml(s.source_url),live=liveState(html);if(live.price==null){results.push({id:item.id,name:p?.canonical_name||null,valid:false,reason:'No se pudo confirmar el precio actual'});continue}const currentSale=sale(live.price,rule),qty=Math.max(1,Math.min(10,Number(item.qty)||1));results.push({id:item.id,name:p?.canonical_name||null,brand:p?.brand||null,image:p?.image_url||null,qty,inStock:live.inStock,currentSalePrice:currentSale,valid:Boolean(live.inStock),reason:live.inStock?null:'Agotado actualmente'})}catch(e){results.push({id:item.id,name:p?.canonical_name||null,valid:false,reason:'No se pudo validar con el proveedor'})}}
const allValid=results.length===items.length&&results.every(x=>x.valid);const total=allValid?results.reduce((sum,x)=>sum+x.currentSalePrice*x.qty,0):null;res.setHeader('Cache-Control','no-store');res.status(200).json({ok:true,allValid,verifiedAt:new Date().toISOString(),total,currency:'MXN',items:results})}catch(e){res.status(500).json({ok:false,error:e.message})}}
